### ISSUE TITLE
Broken image on admin page share box

### ISSUE THREAD

**Issue by joshp23** [joshp23/YOURLS-IQRCodes#13]
When the admin page loads and I open the share box for a particular link the image is broken. I think this has something to do with #2 

If I re-open the link (press the share icon a second time) the image loads fine, and every subsequent image loads just fine.

**Comment by joshp23** [comment]
Fixed with [7ea9461](https://github.com/joshp23/YOURLS-IQRCodes/commit/7ea9461c29f99089c1862ceb25eae15c8a471812) and stable in latest [release](https://github.com/joshp23/YOURLS-IQRCodes/releases/latest) (=>1.1.3).

**Comment by joshp23** [comment]
The above fix still works as intended, but it appears as if there is a second reason that **this issue** occurs which **has something to do with how srv.php creates time sensitive links.** So, while the above fix works 95% of the time, the same effect will randomly occur. 

Probably _will just switch to cookies to solve the issue at some time in the future._ Not high on priority list.

**Comment by jkrobin** [comment]
A quick thank you to you all, and also a note to let you know that I, too, am still experiencing this issue with the broken QR image in the admin page share box. Subsequent loads/presses of the share icon do not fix the issue -- they just never appear in the share box.

All QR codes have, however, been generated through the bulk generation function in settings.

**Comment by joshp23** [comment]
Do they show up in the share box of the stats page?

**Comment by jkrobin** [comment]
@joshp23  No, they don't show in the share box of the stats page, either.

**Comment by joshp23** [comment]
then you have an issue with your configuration. check that you followed the instructions and try again.
Look through old issues for clues.

**Comment by jkrobin** [comment]
Will do. Thanks.

**Comment by m4th2** [comment]
I have the same issue, admin page loads and I open the share box for a particular link the image is broken.
QR codes are OK in /user/cache/qr even if my logo.png is not inside. But QR codes works fine.
Installed with FTP, user/cache/qr created -> 777 OK
user/plugins/iqrcodes -> 777 OK recursively done.

I do not understand this (i am french and google search do not help me to understand what to do) : 
"Symlink assets/srv.php to YOURLS/pages/srv.php
Symlink assets/qrchk.php to YOURLS/pages/qrchk.php"

It may be the issue solution ... Or not ^^

**Comment by joshp23** [comment]
What happens when you click the share button a second time?

**Comment by m4th2** [comment]
Hi Joshp23, thanks for answer.

Same issue, refresh or second time click do not make png ...

URL broken png :
`<img id="myid" src="http://2go.ovh/srv/?id=iqrcodes&amp;key=9ada5c024108cc4c72718aa2a7810811&amp;fn=qrc_14436b8cd9cfdfa9748868358b414909.png" style="width: 100px; height: 100px;">`

Pictures OK in folder http://2go.ovh/user/cache/qr/ 
[http://2go.ovh/user/cache/qr/qrc_14436b8cd9cfdfa9748868358b414909.png]

Should i copy assets/srv.php into /pages/ folder ? It will solve the issue ?
Should i copy assets/qrchk.php into /pages/ folder ? It will solve the issue ?

I am sure my problem is "simlinks", same issue #20
https://github.com/joshp23/YOURLS-IQRCodes/issues/20

May i used .htaccess to symbolic links ?

**Comment by joshp23** [comment]
@cent20fr Are you, by chance, running under Apache or Nginx? If you are running under Nginx, see this [note](https://github.com/joshp23/YOURLS-IQRCodes#note).

If you don't get the image when you click a second time in the admin page, do they show up in the share page?

I would check to see if any of the following work:

- Check permissions of the assets folder (for apache2)
   `chown -R www-data:www-data /path/to/YOURLS/user/plugins/iqrcodes/assets/`
- sym links, made like so
  - Change directory to the iqrcodes' assets folder
    `cd /path/to/YOURLS/user/plugins/iqrcodes/assets/`
  - Make symlinks
    `ln -s ./qrchk.php /path/to/YOURLS/pages/qrchk.php`
    `ln -s ./srv.php /path/to/YOURLS/pages/srv.php`

If neither of those fix your problem
- Remove the symlinks and copy the files instead:
    `cp ./qrchk.php /path/to/YOURLS/pages/qrchk.php`
    `cp ./qrchk.php /path/to/YOURLS/pages/qrchk.php`

Did any of those suggestions fix your issue?

@jkrobin Did you solve your problem, is any of this useful?

**Comment by joshp23** [comment]
@cent20fr If you still experience issues, I noticed that there seems to be something odd in your URL.  Here's what a good qrcode image url looks like:  
`https://example.com/srv/?id=iqrcodes&key=HASH_STRING&fn=qrc_HASH_STRING.png`  
here's yours:
`https://example.com/srv/?id=iqrcodes&amp;key=HASH_STRING&amp;fn=qrc_HASH_STRING.png`
Do those **amp;**'s appear in your url as well?

-------------------
Incidentally, the qrcodes should appear if your system is properly configured. The original broken image bug has been fixed, and is currently tied to a timing issue, and this will be addressed in the future... eventually. See [this comment](https://github.com/joshp23/YOURLS-IQRCodes/issues/13#issuecomment-315393600)

**Comment by m4th2** [comment]
**I've no ssh access, no symlinks possible, so i won't be able to fix my issue by this way.**
(no root access, just free shared hosting for small project, fun tests)

![image](https://user-images.githubusercontent.com/33493725/32688753-3eab92a6-c6d7-11e7-8f17-7de7304f7327.png)

Permissions are good i think.

![image](https://user-images.githubusercontent.com/33493725/32688801-02a5cfb4-c6d8-11e7-89a8-c5032f3d8376.png)

Broken image 

![image](https://user-images.githubusercontent.com/33493725/32688809-24dcbd9a-c6d8-11e7-9b1d-04d9c60e1cb0.png)

URL 

![image](https://user-images.githubusercontent.com/33493725/32688819-499db7d8-c6d8-11e7-81b6-fa312d5bceb9.png)

no "amp;" in URL, just copy - paste  who make it appears... ^^ Sorry for my lack of vigilance.

**I have tried to copy files qrchk.php and srv.php and it works !!!** 

![image](https://user-images.githubusercontent.com/33493725/32688880-75b129e4-c6d9-11e7-9c0b-060951c3295a.png)

**So issue solved,** 

Really thank you very much for helping me, I regret not having dared to make this copy stuck by itself ...

Remove the symlinks and copy the files instead:
```
cp ./qrchk.php /path/to/YOURLS/pages/qrchk.php
cp ./srv.php /path/to/YOURLS/pages/srv.php 
```
qrchk replaced by srv on second ligne of your message.

Tanks a lot,

![image](https://user-images.githubusercontent.com/33493725/32688934-4636169c-c6da-11e7-9c42-8734b1f71211.png)

# Solution : 

If you do not have the ability to make symlinks, you can try to duplicate the qrchk.php and srv.php files in /path/to/YOURLS/user/plugins/iqrcodes/assets/ and place the copy same (same name, same version ...) in the folder /path/to/YOURLS/pages/

**Comment by joshp23** [comment]
That's a lot of effort just to say that copying the files worked. I'm closing this.
